In [2]:
#====== Basic DS packages
import pandas as pd
import numpy as np
#===== FOR POSTGRES READ
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine
#==== ML packages
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
#======================
#READ Postgres 
load_dotenv()

database_url = os.getenv("DATABASE_URL")

if not database_url:
    raise RuntimeError("DATABASE_URL is not configured.")

engine = create_engine(database_url)

df = pd.read_sql("SELECT * FROM merged23_25", engine)

print(df.head(5))

   id         album_name     artist_name  score  \
0   1              Lahai          Sampha    8.5
1   2  melodic nostalgia       tomcbumpz    5.0
2   3       OK ORCHESTRA             AJR    1.0
3   4           HELLMODE  Jeff Rosentock    8.0
4   5     Dorothy's Harp   Dorothy Ashby    9.5

                                               notes  listen_year artwork_url  \
0  A smooth R&B infused hip hop album. Opener is ...         2023        None
1  This is a lowfi beats to study to ep. I didn't...         2023        None
2  I decided I need to suffer I guess. AJR is the...         2023        None
3  The dying masterpiece of California garage pun...         2023        None
4  A funky bass and drum beat lay the ground for ...         2023        None

  musicbrainz_release_id artwork_status
0                   None        pending
1                   None        pending
2                   None        pending
3                   None        pending
4                   None        pending

In [41]:
print(df.dtypes)

id               int64
album_name         str
artist_name        str
score          float64
notes              str
listen_year      int64
dtype: object

In [42]:
def check_data(df):

    missing_count = 0

    for col in df.columns:

        if pd.api.types.is_numeric_dtype(df[col]):

            missing_count += df[col].isna().sum()
            df[col] = df[col].fillna(round(df[col].mean()))

        elif pd.api.types.is_string_dtype(df[col]):

            missing_count += df[col].isna().sum()
            df[col] = df[col].fillna("unprovided/unknown")

        else:
            raise ValueError(
                f"Column type not recognized: {df[col].dtype}"
            )
    print("Table is in Expected Format")
    print(f"Table Shape: {df.shape}")
    print(f"Number of Missing Values Filled: {missing_count}")
    return(df)

def process_string(df, col_name):
    ''' 
    A Function to handle string columns specifically for ML
    '''
    if not pd.api.types.is_string_dtype(df[col_name]):
        print("Non-string column detected. No alterations made.")
        return df

    new_name = "clean_" + col_name

    df[new_name] = (
        df[col_name]
        .str.replace('\n', ' ', regex=False)
        .str.lower()
        .str.strip()
    )

    print(f"{col_name} column regularized")
    return df

def CLEAN(df):
    df=check_data(df)
    print("================")
    for column in df.columns:
        df=process_string(df, column)
        print("================")
    print("Checks are done")
    return(df)

clean_df=CLEAN(df)
clean_df["rev_text"] = (
    clean_df["clean_album_name"] + " "
    + clean_df["clean_artist_name"] + " "
    + clean_df["clean_notes"]
)
newcols=['id', 'score','listen_year',
      'rev_text']
clean_df=clean_df[newcols]
clean_df.head(5)

Table is in Expected Format
Table Shape: (744, 6)
Number of Missing Values Filled: 4
================
Non-string column detected. No alterations made.
================
album_name column regularized
================
artist_name column regularized
================
Non-string column detected. No alterations made.
================
notes column regularized
================
Non-string column detected. No alterations made.
================
Checks are done

   id  score  listen_year                                           rev_text
0   1    8.5         2023  lahai sampha a smooth r&b infused hip hop albu...
1   2    5.0         2023  melodic nostalgia tomcbumpz this is a lowfi be...
2   3    1.0         2023  ok orchestra ajr i decided i need to suffer i ...
3   4    8.0         2023  hellmode jeff rosentock the dying masterpiece ...
4   5    9.5         2023  dorothy's harp dorothy ashby a funky bass and ...

In [43]:
X = clean_df[["rev_text", "listen_year"]]
y = clean_df["score"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)
#========================= Different model comparisons
year_model = Pipeline([
    ("scaler", StandardScaler()),
    ("regressor", Ridge(alpha=10))
])
text_model = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            max_features=10_000,
            ngram_range=(1, 2),
            min_df=1,
            max_df=1.0
        )
    ),
    ("regressor", Ridge(alpha=10))
])

preprocessor = ColumnTransformer([
    (
        "text",
        TfidfVectorizer(
            max_features=20_000,
            ngram_range=(1, 2),
            min_df=1,
            max_df=1.0
        ),
        "rev_text"
    ),
    (
        "year",
        StandardScaler(),
        ["listen_year"]
    )
])

combined_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", Ridge(alpha=10))
])

In [44]:
#MODEL FITTING
year_model.fit(
    X_train[["listen_year"]],
    y_train
)

text_model.fit(
    X_train["rev_text"],
    y_train
)

combined_model.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('text',
                                                  TfidfVectorizer(max_features=20000,
                                                                  ngram_range=(1,
                                                                               2)),
                                                  'rev_text'),
                                                 ('year', StandardScaler(),
                                                  ['listen_year'])])),
                ('regressor', Ridge(alpha=10))])

In [45]:
#-==========================
year_predictions = year_model.predict(
    X_test[["listen_year"]]
)

text_predictions = text_model.predict(
    X_test["rev_text"]
)

combined_predictions = combined_model.predict(
    X_test)

In [46]:
def evaluate_model(name, predictions, y_test):
    rounded = (predictions * 2).round() / 2

    mae = mean_absolute_error(y_test, predictions)
    rmse = mean_squared_error(y_test, predictions) ** 0.5
    r2 = r2_score(y_test, predictions)

    exact = (rounded == y_test).mean()
    within_half = (abs(rounded - y_test) <= 0.5).mean()

    print(f"\n{name}")
    print("-" * len(name))
    print(f"MAE:               {mae:.3f}")
    print(f"RMSE:              {rmse:.3f}")
    print(f"R²:                {r2:.3f}")
    print(f"Exact rating:      {exact:.2%}")
    print(f"Within 0.5 points: {within_half:.2%}")


evaluate_model("Year only", year_predictions, y_test)
evaluate_model("Text only", text_predictions, y_test)
evaluate_model("Text + Year", combined_predictions, y_test)

Year only
---------
MAE:               1.170
RMSE:              1.550
R²:                -0.001
Exact rating:      16.11%
Within 0.5 points: 38.26%

Text only
---------
MAE:               1.064
RMSE:              1.428
R²:                0.150
Exact rating:      16.11%
Within 0.5 points: 42.95%

Text + Year
-----------
MAE:               1.079
RMSE:              1.443
R²:                0.133
Exact rating:      15.44%
Within 0.5 points: 42.28%

In [47]:
#Making score bins for stratified cross-validation
print(clean_df["score"].value_counts().sort_index())

score_bins = pd.cut(
    clean_df["score"],
    bins=[-0.01, 5, 6.5, 7.5, 8.5, 10],
    labels=[
        "low",
        "mid_low",
        "mid",
        "high",
        "very_high"
    ]
)

print(score_bins.value_counts().sort_index())

score
0.0       1
1.0       3
1.5       1
2.0       6
2.5       1
3.0       7
3.5       4
4.0      10
4.5      11
5.0      10
5.5      21
6.0      51
6.5      81
7.0     140
7.5     112
8.0     123
8.5      72
9.0      60
9.5      16
10.0     14
Name: count, dtype: int64
score
low           54
mid_low      153
mid          252
high         195
very_high     90
Name: count, dtype: int64

In [48]:
#Stratified train-test split
X = clean_df["rev_text"]
y = clean_df["score"]

score_bins = pd.cut(
    y,
    bins=[-0.01, 5, 6.5, 7.5, 8.5, 10],
    labels=False
)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=score_bins
)

print("Training:", X_train.shape)
print("Test:", X_test.shape)

Training: (595,)
Test: (149,)

In [49]:
#Distribution of sample sets check
print("Overall:")
print(score_bins.value_counts(normalize=True).sort_index())

print("\nTrain:")
print(pd.cut(
    y_train,
    bins=[-0.01, 5, 6.5, 7.5, 8.5, 10],
    labels=False
).value_counts(normalize=True).sort_index())

print("\nTest:")
print(pd.cut(
    y_test,
    bins=[-0.01, 5, 6.5, 7.5, 8.5, 10],
    labels=False
).value_counts(normalize=True).sort_index())

Overall:
score
0    0.072581
1    0.205645
2    0.338710
3    0.262097
4    0.120968
Name: proportion, dtype: float64

Train:
score
0    0.072269
1    0.205042
2    0.339496
3    0.262185
4    0.121008
Name: proportion, dtype: float64

Test:
score
0    0.073826
1    0.208054
2    0.335570
3    0.261745
4    0.120805
Name: proportion, dtype: float64

In [50]:


# Create strata for the TRAINING data only
train_score_bins = pd.cut(
    y_train,
    bins=[-0.01, 5, 6.5, 7.5, 8.5, 10],
    labels=False
)

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
#-------------
text_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("ridge", Ridge())
])
#===============
param_grid = {
    "tfidf__max_features": [5_000, 10_000, 20_000],
    "tfidf__ngram_range": [(1, 1), (1, 3), (1, 5)],
    "tfidf__min_df": [1, 2, 3],
    "ridge__alpha": [0.1, 1, 10, 100]
}

In [51]:
grid_search = GridSearchCV(
    text_pipeline,
    param_grid,
    cv=cv.split(X_train, train_score_bins),
    scoring="neg_mean_absolute_error",
    n_jobs=1,
    verbose=1
)

grid_search.fit(
    X_train,
    y_train
)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(cv=<generator object _BaseKFold.split at 0x0000015F63D909D0>,
             estimator=Pipeline(steps=[('tfidf', TfidfVectorizer()),
                                       ('ridge', Ridge())]),
             n_jobs=1,
             param_grid={'ridge__alpha': [0.1, 1, 10, 100],
                         'tfidf__max_features': [5000, 10000, 20000],
                         'tfidf__min_df': [1, 2, 3],
                         'tfidf__ngram_range': [(1, 1), (1, 3), (1, 5)]},
             scoring='neg_mean_absolute_error', verbose=1)

In [52]:
print("Best parameters:")
print(grid_search.best_params_)

print("\nBest CV MAE:")
print(-grid_search.best_score_)
#=====================
best_text_model = grid_search.best_estimator_

tuned_predictions = best_text_model.predict(X_test)

evaluate_model(
    "Tuned Text Model",
    tuned_predictions,
    y_test
)

Best parameters:
{'ridge__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__min_df': 1, 'tfidf__ngram_range': (1, 5)}

Best CV MAE:
0.7447219058304355

Tuned Text Model
----------------
MAE:               0.822
RMSE:              1.164
R²:                0.427
Exact rating:      22.15%
Within 0.5 points: 59.73%

In [54]:
#NEXT: 
results = pd.DataFrame({
    "actual": y_test,
    "predicted": tuned_predictions,
    "error": tuned_predictions - y_test,
    "abs_error": abs(tuned_predictions - y_test),
    "text": X_test
})

results = results.sort_values("abs_error", ascending=False)

results.head(10)

,actual,predicted,error,abs_error,text
106,1.0,6.020111,5.020111,5.020111,glitterbug the wombats an mgmt wave band ive n...
517,2.5,6.991995,4.491995,4.491995,"the head hurts, but the heart knows the truth ..."
84,2.0,5.582544,3.582544,3.582544,<|°_°|> caravan palace oh god it's opening wit...
114,2.0,5.293949,3.293949,3.293949,reputation taylor swift hyperpop taylor?! im n...
330,3.0,6.053218,3.053218,3.053218,all the pretty horses current 93 experimental ...
276,2.0,4.782208,2.782208,2.782208,mother ship' dance gavin dance sounds like cra...
252,4.5,6.835204,2.335204,2.335204,songs for the deaf queens of the stone age ope...
147,10.0,7.732086,-2.267914,2.267914,the glow pt. 2 the microphones beautiful waves...
145,4.5,6.627376,2.127376,2.127376,why would i watch hot mulligan ok so imagine y...
10,5.5,7.459115,1.959115,1.959115,open season the high highs. airy piano opener....

In [63]:
new_review=r"poopoopeepee"

In [64]:

prediction = best_text_model.predict([new_review.lower().strip()])
print(prediction[0])

7.217401883192424